### ISSUE TITLE
Some enhancement to the GraphQL Queries and Mutations regarding User objects

### ISSUE THREAD

**Issue by nayakastha** [dscnitrourkela/project-nutella#22]
1. Can we send the firebase UID to the database? That argument is missing in createUser() mutation.
2. On creating a user, there exists some duplication error. 
![Screenshot (225)](https://user-images.githubusercontent.com/58568514/126300756-eaf84b86-a98f-4ab5-8084-89f8788fd658.png)

3. There are two attributes in the User object - QuizzIds and Quizzes! Can we remove one?

**Comment by nayakastha** [comment]
@abhibhaw @riteshsp2000 look into it.

**Comment by riteshsp2000** [comment]
1. There is no need to send the uid. You will have to send the jwt after login which can be obtained through getIdToken method on auth object. All other firebase details such as uid/roles can be obtained from this jwt on server.

2. Fields such as phone number/emails, uids have the property unique set as true. This is to make sure that multiple users from same email/phonenumber arent created

3. I agree. The quizIds field is redundant as the same can be gotten through quizzes, ill update it
