### ISSUE TITLE
Changes needed in Schema

### ISSUE THREAD

**Issue by nayakastha** [dscnitrourkela/project-nutella#27]
1. The createUser Mutation is failing. It works on Localhost but on the deployed version, there is an error.
![Screenshot (228)](https://user-images.githubusercontent.com/58568514/127366260-c61e2cb0-01c2-42de-a6c1-15c6065e0353.png)

2.  For the quiz entry points -
- We need three queries - getLiveQuiz, getPastQuiz, getUpcomingQuiz - it would be good if we can get the computation done on the backend because Flutter isn't compute-intensive.
- For the question type - there are a set of comprehension type questions - we have to figure out a way of storing them alongside the needed questions
- since all questions are in the scheme of +3/-1, are we having a choice to adjust the marking scheme from the admin panel?

**Comment by nayakastha** [comment]
@SriramPatibanda check the list once and add if any changes are required.

**Comment by riteshsp2000** [comment]
Okay cool ill setup the needed things!
